In [36]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
data = {
    'Student_ID': range(1, 11),
    'Math_Score': [78, 85, np.nan, 65, 99, 45, 88, 92, 110, 60],
    'Science_Score': [82, 79, 88, 94, np.nan, 50, 95, 101, 77, 65],
    'English_Score': [70, 75, 80, 60, 90, 55, 85, 100, 95, np.nan],
    'Attendance': [85, 90, 80, 70, 95, 50, 88, 100, 105, 65]  # Notice 105% attendance (error)
}

df = pd.DataFrame(data)
df.head()

   Student_ID  Math_Score  Science_Score  English_Score  Attendance
0           1        78.0           82.0           70.0          85
1           2        85.0           79.0           75.0          90
2           3         NaN           88.0           80.0          80
3           4        65.0           94.0           60.0          70
4           5        99.0            NaN           90.0          95

In [9]:
df.isnull().sum()

Student_ID       0
Math_Score       1
Science_Score    1
English_Score    1
Attendance       0
dtype: int64

In [26]:
df['Math_Score'].fillna(df['Math_Score'].mean(),inplace=True)
df['Science_Score'].fillna(df['Science_Score'].mean(),inplace=True)
df['English_Score'].fillna(df['English_Score'].mean(),inplace=True)

C:\Users\YASH\AppData\Local\Temp\ipykernel_12604\1779060436.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Math_Score'].fillna(df['Math_Score'].mean(),inplace=True)
C:\Users\YASH\AppData\Local\Temp\ipykernel_12604\1779060436.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Science_Score'].fillna(df['Science_Score'].mean(),inplace=True)
C:\Users\YASH\AppData\Local\Temp\ipykernel_12604\1779060436.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['English_Score'].fillna(df['English_Score'].mean(),inplace=True)

In [28]:
df.isnull().sum()

Student_ID       0
Math_Score       0
Science_Score    0
English_Score    0
Attendance       0
dtype: int64

In [30]:
df['Attendance'] = df['Attendance'].apply(lambda x: 100 if x > 100 else x)

In [32]:
def detect_outliers(series):
    Q1=series.quantile(0.25)
    Q3=series.quantile(0.75)
    IQR=Q3 - Q1
    lower_bound=Q1-1.5*IQR
    upper_bound=Q3+1.5*IQR
    return series[(series < lower_bound) | (series > upper_bound)]

numeric_cols = ['Math_Score', 'Science_Score', 'English_Score', 'Attendance']
for col in numeric_cols:
    outliers = detect_outliers(df[col])
    print(f"Outliers in {col}:")
    print(outliers)

Outliers in Math_Score:
Series([], Name: Math_Score, dtype: float64)
Outliers in Science_Score:
5    50.0
Name: Science_Score, dtype: float64
Outliers in English_Score:
Series([], Name: English_Score, dtype: float64)
Outliers in Attendance:
Series([], Name: Attendance, dtype: int64)

In [44]:
# Cap scores at 100
df['Math_Score'] = df['Math_Score'].apply(lambda x: 100 if x > 100 else x)
df['Science_Score'] = df['Science_Score'].apply(lambda x: 100 if x > 100 else x)

In [48]:
df['Math_Score']=np.log(df['Math_Score'])

In [50]:
df['Math_Score']

0    4.356709
1    4.442651
2    4.384801
3    4.174387
4    4.595120
5    3.806662
6    4.477337
7    4.521789
8    4.605170
9    4.094345
Name: Math_Score, dtype: float64

In [52]:
df

   Student_ID  Math_Score  Science_Score  English_Score  Attendance
0           1    4.356709      82.000000      70.000000          85
1           2    4.442651      79.000000      75.000000          90
2           3    4.384801      88.000000      80.000000          80
3           4    4.174387      94.000000      60.000000          70
4           5    4.595120      81.222222      90.000000          95
5           6    3.806662      50.000000      55.000000          50
6           7    4.477337      95.000000      85.000000          88
7           8    4.521789     100.000000     100.000000         100
8           9    4.605170      77.000000      95.000000         100
9          10    4.094345      65.000000      78.888889          65